services:
  cache-build:
    build:
      dockerfile: dockerfile/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: ["sh", "-c", "cargo run"]

  cache-dynamo:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
