name: Build

on:
  push:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: add permission
        run: echo "BUILDX_BAKE_ENTITLEMENTS_FS=0" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
#
#      - name: Cache Docker layers
#        uses: actions/cache@v4
#        with:
#          path: /tmp/.buildx-cache
#          key: ${{ runner.os }}-buildx
#          restore-keys: |
#            ${{ runner.os }}-buildx

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: docker buildx bake --file docker-compose.yaml --file docker-compose-cache.json

#      - name: Save cache
#        uses: actions/cache/save@v4
#        with:
#          path: /tmp/out/.buildx-cache
#          key: ${{ runner.os }}-buildx

      - name: run command
        run: docker compose up --exit-code-from cache-build

  actions-timeline:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2